#include 'fw-tlpp-core.th'
#include 'protheus.ch'

function DsExecStatement(aEmailList as array)
    Local aArea     := FwGetArea() as array
    Local cQuery    := "" as character
    Local oExec     as object
    Local nEmail    := 0 as integer

    fwnulldefault aEmailList := {}

    cQuery := "SELECT COUNT(1) AS COUNT FROM " + RetSqlName("SA1") + " WHERE A1_EMAIL = ? AND D_E_L_E_T_ = ?"

    If Len(aEmailList) > 0
        oExec := FwExecStatement():New(ChangeQuery(cQuery))
    Else
        CONOUT("A LISTA DE E-MAIL ESTA VAZIA!!!")
    EndIf

    For nEmail := 1 to Len(aEmailList)
        oExec:SetString(1, aEmailList[nEmail])
        oExec:SetString(2, ' ')

        cAlias := oExec:OpenAlias()

        If (cAlias)->COUNT > 1
            CONOUT("E-MAIL DUPLICADO: " + aEmailList[nEmail])
        Else
            CONOUT("E-MAIL NÃO DUPLICADO")
        Endif

        (cAlias)->(DbCloseArea())
    next

    If Len(aEmailList) > 0
        oExec:Destroy()
    EndIf
    
    FwFreeObj( oExec )
    FwRestArea( aArea )
return 
